In [45]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pymongo as pm

In [46]:
import json

In [13]:
lis = pd.read_csv('data_proyecto/listings_limpios.csv', sep ='\t')

In [35]:
lis

,id,name,host_id,neighbourhood,property_type,accommodates,bathrooms,bedrooms,beds,price,...,air conditioning,hot water,elevator,family/kid friendly,host greets you,first aid kit,room_type_Entire home/apt,room_type_Private room,room_type_Shared room,is_popular
0,2818,Quiet Garden View Room & Super Fast WiFi,3159,Indische Buurt,Apartment,2,1.5,1.0,2.0,59.0,...,0,1,0,0,1,1,0,1,0,1
1,20168,100%Centre-Studio 1 Private Floor/Bathroom,59484,Grachtengordel,Townhouse,2,1.0,1.0,1.0,80.0,...,0,1,0,0,1,0,1,0,0,0
2,27886,"Romantic, stylish B&B houseboat in canal district",97647,Westelijke Eilanden,Houseboat,2,1.0,1.0,1.0,150.0,...,0,0,0,0,0,0,0,1,0,1
3,28658,Cosy guest room near city centre -1,123414,Bos en Lommer,Apartment,2,1.0,1.0,2.0,65.0,...,0,1,0,0,1,1,0,1,0,0
4,29051,Comfortable single room,124245,Amsterdam Centrum,Apartment,1,1.0,1.0,1.0,55.0,...,0,1,0,0,1,0,0,1,0,1
5,38266,Nice and quiet place in the Jordaan,164204,Jordaan,Apartment,2,1.0,1.0,1.0,145.0,...,0,1,0,0,0,0,1,0,0,1
6,41125,Amsterdam Center Entire Apartment,178515,Jordaan,Apartment,2,0.0,1.0,1.0,180.0,...,0,1,0,1,0,1,1,0,0,0
7,42970,Comfortable room@PERFECT location + 2 bikes,187580,Amsterdam Centrum,Bed and breakfast,2,1.0,1.0,1.0,159.0,...,0,0,0,1,0,1,0,1,0,1
8,44129,Luxury design with canal view,187728,Jordaan,Apartment,3,1.5,1.0,1.0,250.0,...,0,1,0,1,0,0,1,0,0,1
9,50518,Perfect central Amsterdam apartment,231806,Frederik Hendrikbuurt,Apartment,2,1.0,1.0,1.0,125.0,...,0,1,0,1,0,0,1,0,0,1
10,50523,B & B de 9 Straatjes (city center),231946,Grachtengordel,Bed and breakfast,2,1.0,1.0,2.0,115.0,...,0,1,0,1,0,0,0,1,0,1
11,50570,Bright Apartment - residential area,232321,Bos en Lommer,Apartment,3,1.0,1.0,3.0,90.0,...,0,0,0,1,0,1,1,0,0,0
12,53671,Nice room near centre with en suite bath,247822,Spaarndammer en Zeeheldenbuurt,Guest suite,2,1.0,1.0,1.0,75.0,...,0,1,1,1,1,0,0,1,0,0
13,53692,Large quiet Studio with gardenview in hip area.,246493,Oud-Zuid,Guest suite,4,1.0,1.0,3.0,60.0,...,0,1,0,1,0,0,0,1,0,0
14,55256,Luminous central room,260785,Amsterdam Centrum,Apartment,2,1.0,1.0,1.0,86.0,...,0,1,0,1,1,0,0,1,0,0
15,55621,"Fully equiped house, PIJP area = great",262846,Oud-Zuid,Apartment,4,1.0,2.0,4.0,275.0,...,0,1,1,1,1,1,1,0,0,0
16,55703,groundfloor apartment with patio,263214,Bos en Lommer,Apartment,4,1.0,3.0,3.0,250.0,...,0,1,0,1,1,1,1,0,0,0
17,55709,Bright Loft in Centre Amsterdam,263233,Grachtengordel,Loft,3,1.0,1.0,1.0,159.0,...,0,1,1,0,1,1,1,0,0,0
18,55807,"Greatly located, cozy atmosphere",263844,Oud-West,Apartment,2,1.0,1.0,1.0,60.0,...,0,0,0,1,0,0,0,1,0,1
19,55868,Apartment near Museumplein (centre),264178,Oud-Zuid,Apartment,4,1.5,2.0,4.0,149.0,...,1,1,0,1,1,0,1,0,0,0
20,62015,"Charming, beautifully & sunny place",301340,Indische Buurt,Apartment,2,1.0,1.0,1.0,109.0,...,0,1,0,0,1,1,1,0,0,0
21,65230,Juwelier,213960,Amsterdam Centrum,Apartment,4,1.0,NaN,3.0,179.0,...,0,1,0,0,1,0,1,0,0,0
22,68290,Rebel - Private Room,336950,De Wallen,Serviced apartment,2,1.5,1.0,2.0,109.0,...,0,1,0,0,0,1,0,1,0,1
23,68873,Yves Klein - Private Room,336950,Amsterdam Centrum,Serviced apartment,2,1.5,1.0,2.0,109.0,...,0,1,0,1,1,1,0,1,0,1
24,69042,Cozy Studio || Located at the canal!,344312,Jordaan,Bed and breakfast,2,1.0,1.0,1.0,108.0,...,0,0,0,1,0,1,0,1,0,0
25,73917,B28 Unique Houseboat Herengracht,387205,Grachtengordel,Houseboat,2,1.0,1.0,2.0,175.0,...,0,1,0,0,1,1,1,0,0,1
26,74367,Dutch designer canal house apartment (city cen...,391075,Jordaan,Apartment,3,1.0,2.0,2.0,260.0,...,0,1,0,1,1,0,1,0,0,0
27,75382,Garden Suite Studiohttps://www.airbnb.com/mana...,399879,Indische Buurt,Apartment,3,1.0,1.0,2.0,105.0,...,0,1,0,1,0,0,0,1,0,1
28,75444,Cottage Room- Completely Private,399879,Indische Buurt,Apartment,2,1.0,1.0,1.0,70.0,...,0,1,0,0,1,1,0,1,0,1
29,76668,"studio INN, bright and spacious",409579,Westelijke Eilanden,Bed and breakfast,4,1.0,2.0,2.0,135.0,...,0,1,0,1,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49925,32884416,Sweet dreams,127140522,Esquilino,Serviced apartment,2,1.0,1.0,1.0,60.0,...,0,0,0,0,0,1,0,1,0,0
49926,32885723,AC FLAMINIO GUEST HOUSE,188267189,Parioli,Bed and breakfast,2,1.0,1.0,1.0,150.0,...,1,0,1,0,0,0,0,1,0,0
49927,32886146,A cozy room at metro A,9646179,San Giovanni,Condominium,2,1.0,1.0,2.0,32.0,...,1,1,1,0,1,0,0,1,0,0
49928,32886416,BORGO DEI CENTURIONE,247383143,NaN,Guest suite,2,1.0,1.0,1.0,60.0,...,1,0,0,0,0,0,0,1,0,0
49929,32886626,BORGO DEI CENTURIONE,247383143,NaN,Guest suite,2,1.0,1.0,1.0,60.0,...,1,0,0,0,0,0,0,1,0,0
49930,32886816,BORGO DEI CENTURIONE,247383143,NaN,Guest suite,2,1.0,1.0,1.0,60.0,...,1,0,0,0,0,0,0,1,0,0
49931,32887211,AC FLAMINIO GUEST HOUSE,188267189,Parioli,Bed and breakfast,2,1.0,1.0,1.0,150.0,...,1,0,1,0,0,0,0,1,0,0
49932,32887340,BORGO DEI CENTURIONE,247383143,NaN,Guest suite,2,1.0,1.0,1.0,60.0,...,1,0,0,0,0,0,0,1,0,0
49933,32887464,AC FLAMINIO GUEST HOUSE,188267189,Flaminio,Bed and breakfast,2,1.0,1.0,1.0,150.0,...,1,0,1,0,0,0,0,1,0,0
49934,32887929,Old white house,247347328,Esquilino,Apartment,3,1.0,1.0,3.0,65.0,...,0,0,0,0,0,0,0,1,0,0
49935,32890375,Style and Relax in the city center,247248280,Roma Centro,Boutique hotel,3,1.0,1.0,1.0,220.0,...,1,0,0,0,0,0,0,1,0,0
49936,32891786,New experience,247454869,NaN,Apartment,4,1.0,1.0,2.0,50.0,...,0,0,1,0,0,1,1,0,0,0
49937,32892158,LOFT/MONOLOCALE TOR VERGATA - METRO C,197509387,NaN,Tiny house,2,1.0,1.0,1.0,35.0,...,1,1,0,0,1,0,1,0,0,0
49938,32906180,ostia antica suite b&b,234678117,NaN,Serviced apartment,2,1.0,1.0,2.0,50.0,...,1,0,0,0,0,1,0,1,0,0
49939,32907194,"Amour, Friendly Rentals",238441721,Esquilino,Apartment,4,1.0,1.0,1.0,81.0,...,1,0,0,0,0,0,1,0,0,0
49940,32907200,"Liber, Friendly Rentals",238441721,Prati,Apartment,4,1.0,0.0,1.0,91.0,...,1,0,1,0,0,0,1,0,0,0
49941,32907211,"Tasso Aparment, Friendly Rentals",238441721,Roma Centro,Apartment,4,1.0,1.0,1.0,75.0,...,1,0,0,0,0,0,1,0,0,0
49942,32907216,"Hermes, Friendly Rentals",238441721,Prati,Apartment,4,1.0,1.0,1.0,60.0,...,1,0,1,0,0,0,1,0,0,0
49943,32907220,"Hermes II, Friendly Rentals",238441721,Prati,Apartment,4,1.0,0.0,1.0,50.0,...,1,0,1,0,0,0,1,0,0,0
49944,32907226,"Hermes IV, Friendly Rentals",238441721,Prati,Apartment,4,1.0,1.0,1.0,60.0,...,1,0,1,0,0,0,1,0,0,0
49945,32907232,"Hermes V, Friendly Rentals",238441721,Prati,Apartment,4,1.0,1.0,1.0,60.0,...,1,0,1,0,0,0,1,0,0,0
49946,32907238,"Pearl I, Friendly Rentals",238441721,Trastevere,Apartment,4,1.0,1.0,1.0,60.0,...,1,0,0,0,0,0,1,0,0,0
49947,32907243,"Pearl II, Friendly Rentals",238441721,Trastevere,Apartment,2,1.0,0.0,1.0,55.0,...,1,0,1,0,0,0,1,0,0,0
49948,32907247,"Pearl III, Friendly Rentals",238441721,Trastevere,Apartment,4,1.0,1.0,1.0,60.0,...,1,0,1,0,0,0,1,0,0,0
49949,32908001,Your Double Room just a few steps from Vatican IV,242671341,Prati,Boutique hotel,2,1.0,1.0,1.0,80.0,...,1,0,0,0,1,0,0,1,0,0
49950,32908117,Your Junior Suite a few steps from the Vatican V,242671341,Prati,Boutique hotel,3,1.0,1.0,2.0,120.0,...,1,0,0,0,1,0,0,1,0,0
49951,32909681,trastevere Sweet dream apartment,5345069,Trastevere,Apartment,5,1.0,2.0,3.0,106.0,...,1,1,0,1,1,1,1,0,0,0
49952,32911147,New Roma,247454869,Nomentana,Apartment,3,1.0,1.0,2.0,50.0,...,0,0,1,0,0,1,1,0,0,0
49953,32911659,SUITE CHIRO' DOUBLE ROOM 15 MINUTES FROM SPAGNA,178446266,Trieste,Apartment,2,1.0,1.0,1.0,50.0,...,1,1,1,1,1,1,0,1,0,0
49954,32912710,Blue Roma B&b - Deluxe Room,161032002,San Giovanni,Bed and breakfast,3,1.0,1.0,3.0,60.0,...,1,0,1,0,0,1,0,1,0,0

In [28]:
lis = lis.drop('Unnamed: 0',1)

In [17]:
connection = pm.MongoClient('localhost', 27017)

In [22]:
database = connection['project']
collection = database['listings']

In [30]:
data = lis.to_dict('records')

In [36]:
collection.insert_many(data)

In [37]:
ejemplo = pd.DataFrame(list(collection.find()))

In [40]:
ejemplo = ejemplo.drop('_id',1)

In [49]:
ejemplo.shape

(49955, 37)

In [62]:
df = pd.DataFrame.from_records(collection.find().sort([( '$natural', 1 )] ))
#"item.category": 1, "item.type": 1

In [63]:
df

,_id,accommodates,air conditioning,availability_365,bathrooms,bedrooms,beds,calculated_host_listings_count,elevator,essentials,...,property_type,review_scores_rating,reviews_per_month,room_type_Entire home/apt,room_type_Private room,room_type_Shared room,shampoo,tv,washer,wifi
0,5cb6718c3036030a63bc9e8c,2,0,15,1.5,1.0,2.0,1,0,1,...,Apartment,97.0,2.07,0,1,0,1,0,1,1
1,5cb6718c3036030a63bc9e8d,2,0,191,1.0,1.0,1.0,2,0,1,...,Townhouse,87.0,2.29,1,0,0,1,1,0,1
2,5cb6718c3036030a63bc9e8e,2,0,125,1.0,1.0,1.0,1,0,1,...,Houseboat,99.0,2.07,0,1,0,1,1,0,1
3,5cb6718c3036030a63bc9e8f,2,0,231,1.0,1.0,2.0,2,0,1,...,Apartment,93.0,4.14,0,1,0,1,1,1,1
4,5cb6718c3036030a63bc9e90,1,0,157,1.0,1.0,1.0,3,0,1,...,Apartment,95.0,4.09,0,1,0,1,0,1,1
5,5cb6718c3036030a63bc9e91,2,0,13,1.0,1.0,1.0,1,0,1,...,Apartment,99.0,1.89,1,0,0,1,1,1,1
6,5cb6718c3036030a63bc9e92,2,0,29,0.0,1.0,1.0,1,0,1,...,Apartment,95.0,0.76,1,0,0,1,1,1,1
7,5cb6718c3036030a63bc9e93,2,0,158,1.0,1.0,1.0,2,0,1,...,Bed and breakfast,98.0,4.22,0,1,0,1,1,1,1
8,5cb6718c3036030a63bc9e94,3,0,10,1.5,1.0,1.0,5,0,1,...,Apartment,98.0,1.69,1,0,0,1,1,1,1
9,5cb6718c3036030a63bc9e95,2,0,12,1.0,1.0,1.0,1,0,1,...,Apartment,96.0,1.19,1,0,0,1,1,1,1
10,5cb6718c3036030a63bc9e96,2,0,180,1.0,1.0,2.0,1,0,1,...,Bed and breakfast,97.0,2.26,0,1,0,0,1,1,1
11,5cb6718c3036030a63bc9e97,3,0,1,1.0,1.0,3.0,2,0,1,...,Apartment,91.0,1.60,1,0,0,1,1,1,1
12,5cb6718c3036030a63bc9e98,2,0,159,1.0,1.0,1.0,1,1,1,...,Guest suite,91.0,2.78,0,1,0,1,1,1,1
13,5cb6718c3036030a63bc9e99,4,0,11,1.0,1.0,3.0,5,0,1,...,Guest suite,91.0,2.52,0,1,0,1,1,1,1
14,5cb6718c3036030a63bc9e9a,2,0,86,1.0,1.0,1.0,1,0,1,...,Apartment,93.0,1.37,0,1,0,1,0,1,1
15,5cb6718c3036030a63bc9e9b,4,0,14,1.0,2.0,4.0,1,1,1,...,Apartment,97.0,0.25,1,0,0,1,1,1,1
16,5cb6718c3036030a63bc9e9c,4,0,65,1.0,3.0,3.0,1,0,1,...,Apartment,100.0,0.07,1,0,0,1,1,1,1
17,5cb6718c3036030a63bc9e9d,3,0,90,1.0,1.0,1.0,1,1,1,...,Loft,100.0,0.52,1,0,0,1,1,1,1
18,5cb6718c3036030a63bc9e9e,2,0,64,1.0,1.0,1.0,1,0,0,...,Apartment,97.0,1.48,0,1,0,0,1,1,1
19,5cb6718c3036030a63bc9e9f,4,1,42,1.5,2.0,4.0,1,0,1,...,Apartment,97.0,0.89,1,0,0,1,1,1,1
20,5cb6718c3036030a63bc9ea0,2,0,25,1.0,1.0,1.0,1,0,1,...,Apartment,99.0,0.22,1,0,0,1,1,1,1
21,5cb6718c3036030a63bc9ea1,4,0,36,1.0,NaN,3.0,1,0,1,...,Apartment,85.0,0.89,1,0,0,1,1,1,1
22,5cb6718c3036030a63bc9ea2,2,0,135,1.5,1.0,2.0,4,0,1,...,Serviced apartment,96.0,6.15,0,1,0,1,1,1,1
23,5cb6718c3036030a63bc9ea3,2,0,137,1.5,1.0,2.0,4,0,1,...,Serviced apartment,96.0,5.53,0,1,0,1,0,1,1
24,5cb6718c3036030a63bc9ea4,2,0,300,1.0,1.0,1.0,2,0,1,...,Bed and breakfast,92.0,1.46,0,1,0,1,1,1,1
25,5cb6718c3036030a63bc9ea5,2,0,65,1.0,1.0,2.0,1,0,1,...,Houseboat,94.0,1.20,1,0,0,1,1,0,1
26,5cb6718c3036030a63bc9ea6,3,0,363,1.0,2.0,2.0,1,0,1,...,Apartment,91.0,0.10,1,0,0,1,0,1,1
27,5cb6718c3036030a63bc9ea7,3,0,12,1.0,1.0,2.0,3,0,1,...,Apartment,95.0,2.00,0,1,0,1,1,1,1
28,5cb6718c3036030a63bc9ea8,2,0,14,1.0,1.0,1.0,3,0,1,...,Apartment,94.0,2.72,0,1,0,1,1,1,1
29,5cb6718c3036030a63bc9ea9,4,0,178,1.0,2.0,2.0,1,0,1,...,Bed and breakfast,98.0,1.37,0,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49925,5cb6718d3036030a63bd6191,2,0,365,1.0,1.0,1.0,3,0,1,...,Serviced apartment,NaN,NaN,0,1,0,1,1,0,1
49926,5cb6718d3036030a63bd6192,2,1,327,1.0,1.0,1.0,3,1,1,...,Bed and breakfast,NaN,NaN,0,1,0,1,1,0,1
49927,5cb6718d3036030a63bd6193,2,1,87,1.0,1.0,2.0,4,1,1,...,Condominium,NaN,NaN,0,1,0,1,0,1,1
49928,5cb6718d3036030a63bd6194,2,1,174,1.0,1.0,1.0,5,0,1,...,Guest suite,NaN,NaN,0,1,0,1,1,0,1
49929,5cb6718d3036030a63bd6195,2,1,174,1.0,1.0,1.0,5,0,1,...,Guest suite,NaN,NaN,0,1,0,1,1,0,1
49930,5cb6718d3036030a63bd6196,2,1,174,1.0,1.0,1.0,5,0,1,...,Guest suite,NaN,NaN,0,1,0,1,1,0,1
49931,5cb6718d3036030a63bd6197,2,1,327,1.0,1.0,1.0,3,1,1,...,Bed and breakfast,NaN,NaN,0,1,0,1,1,0,1
49932,5cb6718d3036030a63bd6198,2,1,180,1.0,1.0,1.0,5,0,1,...,Guest suite,NaN,NaN,0,1,0,1,1,0,1
49933,5cb6718d3036030a63bd6199,2,1,327,1.0,1.0,1.0,3,1,1,...,Bed and breakfast,NaN,NaN,0,1,0,1,1,0,1
49934,5cb6718d3036030a63bd619a,3,0,360,1.0,1.0,3.0,1,0,1,...,Apartment,NaN,NaN,0,1,0,0,1,0,1
49935,5cb6718d3036030a63bd619b,3,1,183,1.0,1.0,1.0,1,0,1,...,Boutique hotel,NaN,NaN,0,1,0,1,1,0,1
49936,5cb6718d3036030a63bd619c,4,0,170,1.0,1.0,2.0,2,1,1,...,Apartment,NaN,NaN,1,0,0,1,1,1,1
49937,5cb6718d3036030a63bd619d,2,1,117,1.0,1.0,1.0,1,0,1,...,Tiny house,NaN,NaN,1,0,0,0,1,1,1
49938,5cb6718d3036030a63bd619e,2,1,358,1.0,1.0,2.0,2,0,1,...,Serviced apartment,NaN,NaN,0,1,0,1,1,0,1
49939,5cb6718d3036030a63bd619f,4,1,292,1.0,1.0,1.0,20,0,1,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49940,5cb6718d3036030a63bd61a0,4,1,235,1.0,0.0,1.0,20,1,1,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49941,5cb6718d3036030a63bd61a1,4,1,354,1.0,1.0,1.0,20,0,1,...,Apartment,NaN,NaN,1,0,0,0,1,0,1
49942,5cb6718d3036030a63bd61a2,4,1,325,1.0,1.0,1.0,20,1,1,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49943,5cb6718d3036030a63bd61a3,4,1,293,1.0,0.0,1.0,20,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49944,5cb6718d3036030a63bd61a4,4,1,332,1.0,1.0,1.0,20,1,1,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49945,5cb6718d3036030a63bd61a5,4,1,316,1.0,1.0,1.0,20,1,1,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49946,5cb6718d3036030a63bd61a6,4,1,68,1.0,1.0,1.0,20,0,1,...,Apartment,NaN,NaN,1,0,0,0,1,0,1
49947,5cb6718d3036030a63bd61a7,2,1,71,1.0,0.0,1.0,20,1,1,...,Apartment,NaN,NaN,1,0,0,0,1,0,1
49948,5cb6718d3036030a63bd61a8,4,1,25,1.0,1.0,1.0,20,1,1,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49949,5cb6718d3036030a63bd61a9,2,1,362,1.0,1.0,1.0,5,0,1,...,Boutique hotel,NaN,NaN,0,1,0,1,1,0,1
49950,5cb6718d3036030a63bd61aa,3,1,362,1.0,1.0,2.0,5,0,1,...,Boutique hotel,NaN,NaN,0,1,0,1,1,0,1
49951,5cb6718d3036030a63bd61ab,5,1,335,1.0,2.0,3.0,13,0,1,...,Apartment,NaN,NaN,1,0,0,1,1,0,1
49952,5cb6718d3036030a63bd61ac,3,0,358,1.0,1.0,2.0,2,1,1,...,Apartment,NaN,NaN,1,0,0,1,1,1,1
49953,5cb6718d3036030a63bd61ad,2,1,363,1.0,1.0,1.0,2,1,1,...,Apartment,NaN,NaN,0,1,0,1,1,0,1
49954,5cb6718d3036030a63bd61ae,3,1,312,1.0,1.0,3.0,2,1,1,...,Bed and breakfast,NaN,NaN,0,1,0,1,1,0,1

In [64]:
df.drop('_id',1)

,accommodates,air conditioning,availability_365,bathrooms,bedrooms,beds,calculated_host_listings_count,elevator,essentials,family/kid friendly,...,property_type,review_scores_rating,reviews_per_month,room_type_Entire home/apt,room_type_Private room,room_type_Shared room,shampoo,tv,washer,wifi
0,2,0,15,1.5,1.0,2.0,1,0,1,0,...,Apartment,97.0,2.07,0,1,0,1,0,1,1
1,2,0,191,1.0,1.0,1.0,2,0,1,0,...,Townhouse,87.0,2.29,1,0,0,1,1,0,1
2,2,0,125,1.0,1.0,1.0,1,0,1,0,...,Houseboat,99.0,2.07,0,1,0,1,1,0,1
3,2,0,231,1.0,1.0,2.0,2,0,1,0,...,Apartment,93.0,4.14,0,1,0,1,1,1,1
4,1,0,157,1.0,1.0,1.0,3,0,1,0,...,Apartment,95.0,4.09,0,1,0,1,0,1,1
5,2,0,13,1.0,1.0,1.0,1,0,1,0,...,Apartment,99.0,1.89,1,0,0,1,1,1,1
6,2,0,29,0.0,1.0,1.0,1,0,1,1,...,Apartment,95.0,0.76,1,0,0,1,1,1,1
7,2,0,158,1.0,1.0,1.0,2,0,1,1,...,Bed and breakfast,98.0,4.22,0,1,0,1,1,1,1
8,3,0,10,1.5,1.0,1.0,5,0,1,1,...,Apartment,98.0,1.69,1,0,0,1,1,1,1
9,2,0,12,1.0,1.0,1.0,1,0,1,1,...,Apartment,96.0,1.19,1,0,0,1,1,1,1
10,2,0,180,1.0,1.0,2.0,1,0,1,1,...,Bed and breakfast,97.0,2.26,0,1,0,0,1,1,1
11,3,0,1,1.0,1.0,3.0,2,0,1,1,...,Apartment,91.0,1.60,1,0,0,1,1,1,1
12,2,0,159,1.0,1.0,1.0,1,1,1,1,...,Guest suite,91.0,2.78,0,1,0,1,1,1,1
13,4,0,11,1.0,1.0,3.0,5,0,1,1,...,Guest suite,91.0,2.52,0,1,0,1,1,1,1
14,2,0,86,1.0,1.0,1.0,1,0,1,1,...,Apartment,93.0,1.37,0,1,0,1,0,1,1
15,4,0,14,1.0,2.0,4.0,1,1,1,1,...,Apartment,97.0,0.25,1,0,0,1,1,1,1
16,4,0,65,1.0,3.0,3.0,1,0,1,1,...,Apartment,100.0,0.07,1,0,0,1,1,1,1
17,3,0,90,1.0,1.0,1.0,1,1,1,0,...,Loft,100.0,0.52,1,0,0,1,1,1,1
18,2,0,64,1.0,1.0,1.0,1,0,0,1,...,Apartment,97.0,1.48,0,1,0,0,1,1,1
19,4,1,42,1.5,2.0,4.0,1,0,1,1,...,Apartment,97.0,0.89,1,0,0,1,1,1,1
20,2,0,25,1.0,1.0,1.0,1,0,1,0,...,Apartment,99.0,0.22,1,0,0,1,1,1,1
21,4,0,36,1.0,NaN,3.0,1,0,1,0,...,Apartment,85.0,0.89,1,0,0,1,1,1,1
22,2,0,135,1.5,1.0,2.0,4,0,1,0,...,Serviced apartment,96.0,6.15,0,1,0,1,1,1,1
23,2,0,137,1.5,1.0,2.0,4,0,1,1,...,Serviced apartment,96.0,5.53,0,1,0,1,0,1,1
24,2,0,300,1.0,1.0,1.0,2,0,1,1,...,Bed and breakfast,92.0,1.46,0,1,0,1,1,1,1
25,2,0,65,1.0,1.0,2.0,1,0,1,0,...,Houseboat,94.0,1.20,1,0,0,1,1,0,1
26,3,0,363,1.0,2.0,2.0,1,0,1,1,...,Apartment,91.0,0.10,1,0,0,1,0,1,1
27,3,0,12,1.0,1.0,2.0,3,0,1,1,...,Apartment,95.0,2.00,0,1,0,1,1,1,1
28,2,0,14,1.0,1.0,1.0,3,0,1,0,...,Apartment,94.0,2.72,0,1,0,1,1,1,1
29,4,0,178,1.0,2.0,2.0,1,0,1,1,...,Bed and breakfast,98.0,1.37,0,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49925,2,0,365,1.0,1.0,1.0,3,0,1,0,...,Serviced apartment,NaN,NaN,0,1,0,1,1,0,1
49926,2,1,327,1.0,1.0,1.0,3,1,1,0,...,Bed and breakfast,NaN,NaN,0,1,0,1,1,0,1
49927,2,1,87,1.0,1.0,2.0,4,1,1,0,...,Condominium,NaN,NaN,0,1,0,1,0,1,1
49928,2,1,174,1.0,1.0,1.0,5,0,1,0,...,Guest suite,NaN,NaN,0,1,0,1,1,0,1
49929,2,1,174,1.0,1.0,1.0,5,0,1,0,...,Guest suite,NaN,NaN,0,1,0,1,1,0,1
49930,2,1,174,1.0,1.0,1.0,5,0,1,0,...,Guest suite,NaN,NaN,0,1,0,1,1,0,1
49931,2,1,327,1.0,1.0,1.0,3,1,1,0,...,Bed and breakfast,NaN,NaN,0,1,0,1,1,0,1
49932,2,1,180,1.0,1.0,1.0,5,0,1,0,...,Guest suite,NaN,NaN,0,1,0,1,1,0,1
49933,2,1,327,1.0,1.0,1.0,3,1,1,0,...,Bed and breakfast,NaN,NaN,0,1,0,1,1,0,1
49934,3,0,360,1.0,1.0,3.0,1,0,1,0,...,Apartment,NaN,NaN,0,1,0,0,1,0,1
49935,3,1,183,1.0,1.0,1.0,1,0,1,0,...,Boutique hotel,NaN,NaN,0,1,0,1,1,0,1
49936,4,0,170,1.0,1.0,2.0,2,1,1,0,...,Apartment,NaN,NaN,1,0,0,1,1,1,1
49937,2,1,117,1.0,1.0,1.0,1,0,1,0,...,Tiny house,NaN,NaN,1,0,0,0,1,1,1
49938,2,1,358,1.0,1.0,2.0,2,0,1,0,...,Serviced apartment,NaN,NaN,0,1,0,1,1,0,1
49939,4,1,292,1.0,1.0,1.0,20,0,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49940,4,1,235,1.0,0.0,1.0,20,1,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49941,4,1,354,1.0,1.0,1.0,20,0,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,0,1
49942,4,1,325,1.0,1.0,1.0,20,1,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49943,4,1,293,1.0,0.0,1.0,20,1,0,0,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49944,4,1,332,1.0,1.0,1.0,20,1,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49945,4,1,316,1.0,1.0,1.0,20,1,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49946,4,1,68,1.0,1.0,1.0,20,0,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,0,1
49947,2,1,71,1.0,0.0,1.0,20,1,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,0,1
49948,4,1,25,1.0,1.0,1.0,20,1,1,0,...,Apartment,NaN,NaN,1,0,0,0,1,1,1
49949,2,1,362,1.0,1.0,1.0,5,0,1,0,...,Boutique hotel,NaN,NaN,0,1,0,1,1,0,1
49950,3,1,362,1.0,1.0,2.0,5,0,1,0,...,Boutique hotel,NaN,NaN,0,1,0,1,1,0,1
49951,5,1,335,1.0,2.0,3.0,13,0,1,1,...,Apartment,NaN,NaN,1,0,0,1,1,0,1
49952,3,0,358,1.0,1.0,2.0,2,1,1,0,...,Apartment,NaN,NaN,1,0,0,1,1,1,1
49953,2,1,363,1.0,1.0,1.0,2,1,1,1,...,Apartment,NaN,NaN,0,1,0,1,1,0,1
49954,3,1,312,1.0,1.0,3.0,2,1,1,0,...,Bed and breakfast,NaN,NaN,0,1,0,1,1,0,1